### ISSUE TITLE
setuptools unfindable

### ISSUE THREAD

**Issue by ghost** [digiflor/Latex2TEI#1]
Hello,
I get this message when trying to install LATEX2TEI : 
![Capture d’écran de 2022-04-11 19-32-02](https://user-images.githubusercontent.com/71893470/162797125-c3a5b057-5ff3-4106-b2a1-95bb400e85bd.png)

What can I do ?
Thanks in advance,
Rémy

**Comment by digiflor** [comment]
Bonjour Remy,
le problème n'est pas en Latex2Tei mais au niveau de Python. Je t'envoi un
lien où tu pourras retrouver "ton" message et les instructions pour
résoudre le problème.
https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools
Marta

Il giorno lun 11 apr 2022 alle ore 19:34 Rémy Ienco <
***@***.***> ha scritto:

**Comment by ghost** [comment]
Merci beaucoup, cette méthode a l'air de fonctionner correctement maintenant !

**Comment by digiflor** [comment]
Merci à toi Rémy,
Je te préviens un peu pour ce qui concerne Latex2TEI: parmi les trois tools
développé, TEI-MED Latex et ULA, Latex2Tei est au niveau "brut". Il s'agit
d'un prototype, réalisé exprès pour l'encodage TEI d'un projet de Valencia,
par rapport auquel il fallait rapidement faire la conversion de centaines
de fichiers Latex en TEI. Il a bien marché et j'ai aidé le projet à
avancer. Donc, le mécanisme qui est à la base fonctionne parfaitement, mais
il n'est pas pleinement User friendly comme TEI-MED, je n'ai pas encore eu
le temps de l'améliorer.
Marta

Il giorno mar 12 apr 2022 alle ore 17:21 Rémy Ienco <
***@***.***> ha scritto:

**Comment by ghost** [comment]
Bonjour Marta,
Je me trouve également dans une situation où nous aurons, à l'Université de Lille, de nombreux fichiers LateX à convertir en TEI. Je me suis servi de Pandoc jusqu'ici, mais les porteurs du projet aimeraient, justement, une solution plus pratique. C'est pourquoi je fais un tour d'horizon des outils développés dans ce sens. Merci en tout cas pour tes précieux conseils !

**Comment by digiflor** [comment]
Bonjour Rémi, si tu veux, on pourrait adapter LaTeX2tei à vos besoins. Une
fois l'outil adapté, vous êtes autonomes dans le travail (et ce serait une
occasion pour reprendre en main ce prototype). Marta

Il mer 13 apr 2022, 10:21 Rémy Ienco ***@***.***> ha scritto:

**Comment by digiflor** [comment]
Ps. Je t'envoie les notes que j'avais écrit pour l'autre projet pour te
faire comprendre son fonctionnement.
Marta

Il mer 13 apr 2022, 10:42 marta materni ***@***.***> ha
scritto:

**Comment by ghost** [comment]
Merci pour ta proposition que j'accepte avec plaisir ! Pour faciliter les échanges et pour que tu m'envoies les notes, tu peux me contacter par mail à l'adresse remy.ienco@proton.me
À bientôt :-)
Rémy
